# Generated by Django 5.0.1 on 2024-01-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_time',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
