# Generated by Django 5.0.1 on 2024-01-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_release_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('스릴러', '스릴러'), ('로맨스', '로맨스'), ('액션', '액션')], max_length=32),
        ),
    ]
