# Generated by Django 5.0.1 on 2024-01-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_like',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
